In [9]:
import pandas as pd
import yfinance as yf
import numpy as np

In [10]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime
from dateutil.relativedelta import relativedelta

# Angegebenes Datum
date_str = '2024-05-31'
date = datetime.strptime(date_str, '%Y-%m-%d')

# Ein Jahr zurück
start_date = date - relativedelta(years=1)

# HTTP GET request to the Wikipedia page
url = 'https://en.wikipedia.org/wiki/Nasdaq-100'
response = requests.get(url)

# Parsing the HTML content of the page 
soup = BeautifulSoup(response.content, 'html.parser')

# Finding all the tables on the page
tables = soup.find_all('table')

# Extracting the fifth table 
index_table = tables[4]

ticker_df = pd.read_html(str(index_table))[0]

In [11]:
tickers = ticker_df['Ticker'].to_list()
ticker_df

,Company,Ticker,GICS Sector,GICS Sub-Industry
0,Adobe Inc.,ADBE,Information Technology,Application Software
1,ADP,ADP,Industrials,Human Resource & Employment Services
2,Airbnb,ABNB,Consumer Discretionary,"Hotels, Resorts & Cruise Lines"
3,Alphabet Inc. (Class A),GOOGL,Communication Services,Interactive Media & Services
4,Alphabet Inc. (Class C),GOOG,Communication Services,Interactive Media & Services
...,...,...,...,...
96,Walgreens Boots Alliance,WBA,Consumer Staples,Drug Retail
97,Warner Bros. Discovery,WBD,Communication Services,Broadcasting
98,"Workday, Inc.",WDAY,Information Technology,Application Software
99,Xcel Energy,XEL,Utilities,Multi-Utilities
100,Zscaler,ZS,Information Technology,Application Software

In [12]:
df = yf.download(tickers,start=start_date)['Adj Close']
df

[*********************100%%**********************]  101 of 101 completed

,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,...,TTD,TTWO,TXN,VRSK,VRTX,WBA,WBD,WDAY,XEL,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2023-05-31,176.313644,109.769997,417.790009,174.359283,204.322632,199.389999,79.633163,132.260620,118.209999,213.964844,...,70.080002,137.729996,168.544037,217.803421,323.570007,28.420347,11.28,211.990005,62.959763,135.479996
2023-06-01,179.138641,112.160004,426.750000,177.028305,207.079636,203.300003,78.579292,133.778702,119.470001,207.778168,...,73.260002,137.589996,170.414825,218.658310,323.619995,28.373554,11.35,215.309998,61.281860,135.089996
2023-06-02,179.994095,118.059998,436.369995,177.274811,211.684448,204.240005,79.949310,133.580261,117.860001,211.463013,...,74.239998,137.520004,169.852615,220.049942,333.779999,29.187706,11.75,213.500000,60.886494,142.389999
2023-06-05,178.631332,115.690002,434.179993,172.522476,211.410721,208.429993,80.476242,132.687256,117.930000,215.157578,...,75.370003,136.720001,165.035141,221.799469,334.420013,29.243855,11.63,213.479996,61.667583,148.050003
2023-06-06,178.263290,117.300003,432.890015,175.470505,211.899536,208.009995,79.939735,132.895645,124.230003,214.517578,...,74.879997,135.679993,165.132080,220.000244,330.410004,29.505880,12.10,215.000000,61.291508,152.990005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-24,189.979996,144.470001,475.429993,232.509995,248.899994,214.889999,88.970001,220.889999,166.360001,305.839996,...,94.750000,154.600006,199.179993,251.580002,456.950012,16.030001,7.73,220.910004,53.720001,171.639999
2024-05-28,189.990005,147.009995,478.429993,233.440002,243.300003,210.449997,88.620003,221.320007,171.610001,300.190002,...,95.089996,156.789993,199.600006,248.869995,446.880005,15.380000,7.87,215.440002,53.740002,164.160004
2024-05-29,190.289993,146.610001,477.600006,228.149994,240.089996,208.509995,87.470001,219.050003,165.139999,296.369995,...,95.449997,159.679993,194.910004,246.919998,441.130005,14.890000,7.66,211.580002,53.299999,164.369995
2024-05-30,191.289993,145.520004,445.869995,230.000000,240.910004,199.929993,88.160004,216.539993,166.750000,301.000000,...,93.709999,159.779999,195.679993,249.369995,443.049988,15.390000,8.08,207.440002,54.320000,156.649994
2024-05-31,192.250000,144.929993,444.760010,234.490005,244.919998,201.600006,90.250000,215.080002,166.899994,305.850006,...,92.779999,160.360001,195.009995,252.779999,455.339996,16.219999,8.24,211.449997,55.450001,169.960007

In [13]:
df = df.dropna(axis=1)
mtl = (df.pct_change() + 1)[1:].resample('M').prod()

In [14]:
def get_rolling_ret(df,n):
    return df.rolling(n).apply(np.prod)

ret_12, ret_6, ret_3 = get_rolling_ret(mtl,12), get_rolling_ret(mtl,6), get_rolling_ret(mtl,3)

In [15]:
import pandas as pd

def get_top(date, df, ret_12, ret_6, ret_3):
    # Get the top stocks
    top_30 = ret_12.loc[date].nlargest(30).index
    top_15 = ret_6.loc[date, top_30].nlargest(15).index
    top_5 = ret_3.loc[date, top_15].nlargest(5).index
    
    # Retrieve the figures for the top 5 stocks within the last 3 months
    top_5_figures_3M = ret_3.loc[date, top_5]
    # Sort the figures in descending order
    top_5_figures_3M = top_5_figures_3M.sort_values(ascending=False)

    # Retrieve the figures for the top 5 stocks within the last 3 months
    top_5_figures_6M = ret_6.loc[date, top_5]
    # Sort the figures in descending order
    top_5_figures_6M = top_5_figures_6M.sort_values(ascending=False)

    # Retrieve the figures for the top 5 stocks within the last 3 months
    top_5_figures_12M = ret_12.loc[date, top_5]
    # Sort the figures in descending order
    top_5_figures_12M = top_5_figures_12M.sort_values(ascending=False)
    
    # Get the current prices for the top 5 stocks
    current_prices = df.loc[date, top_5]
    
    # Calculate the standard deviation for the top 5 stocks' returns
    std_devs_returns = ret_3[top_5].std()

    # Calculate the number of times returns dropped below -10% on a monthly basis
    below_neg_15_percent = (mtl[top_5] < 0.85).sum()
    
    # Calculate the number of times returns dropped below -10% on a monthly basis
    below_neg_10_percent = (mtl[top_5] < 0.90).sum()

    # Calculate the number of times returns dropped below -10% on a monthly basis
    below_neg_7_percent = (mtl[top_5] < 0.93).sum()

    # Calculate the standard deviation of the prices for the top 5 stocks
    std_devs_prices = df[top_5].std()
    
    # Create a DataFrame to hold all the data
    data = {
        'Top 5 Figures last 3M %': (top_5_figures_3M.round(3)-1)*100,
        'Top 5 Figures last 6M %': (top_5_figures_6M.round(3)-1)*100,
        'Top 5 Figures last 12M %': (top_5_figures_12M.round(3)-1)*100,
        'Current Prices': current_prices,
        'Std Dev of Prices': std_devs_prices,
        'Std Dev of Returns': std_devs_returns,
        'Below -7% Return Count last 12M': below_neg_7_percent,
        'Below -10% Return Count last 12M': below_neg_10_percent,
        'Below -15% Return Count last 12M': below_neg_15_percent
    }
    result_df = pd.DataFrame(data)
    
    return result_df

# Assuming date, df, ret_12, ret_6, and ret_3 are defined earlier
result_df = get_top(date, df, ret_12, ret_6, ret_3)

result_df.to_excel(f'Top Performer Nasdaq - {start_date}.xlsx')

print("Top 5 Stocks Data:")
result_df

Top 5 Stocks Data:

,Top 5 Figures last 3M %,Top 5 Figures last 6M %,Top 5 Figures last 12M %,Current Prices,Std Dev of Prices,Std Dev of Returns,Below -7% Return Count last 12M,Below -10% Return Count last 12M,Below -15% Return Count last 12M
CEG,29.4,80.1,160.8,217.250000,38.588705,0.176667,0,0,0
FANG,12.1,32.5,65.4,199.259995,24.805214,0.115875,0,0,0
MU,38.1,64.6,84.4,125.000000,20.389851,0.154640,1,0,0
NVDA,38.6,134.4,189.9,1096.329956,201.824029,0.315507,1,1,0
QCOM,29.8,59.6,84.0,204.050003,27.106657,0.172658,1,1,0

In [16]:
import subprocess
import os

# Email details
file_name = 'Top Performer.xlsx'
file_path = os.path.abspath(file_name)  # Get the absolute path to the file
recipient = "recipient@example.com"  # Replace with the recipient's email address
subject = "Current Top Performer // Nasdaq"
body = "Hi,\n\nwie gehabt, hier die aktuellen Top-Performer.\n\nGruß,\nRobert"

# AppleScript to create a new email draft in Apple Mail with the attachment
apple_script = f'''
tell application "Mail"
    set newMessage to make new outgoing message with properties {{subject:"{subject}", content:"{body}", visible:true}}
    tell newMessage
        make new to recipient at end of to recipients with properties {{address:"{recipient}"}}
        tell content
            make new attachment with properties {{file name:"{file_path}"}} at after the last paragraph
        end tell
    end tell
    activate
end tell
'''

# Run the AppleScript
subprocess.run(['osascript', '-e', apple_script])

CompletedProcess(args=['osascript', '-e', '\ntell application "Mail"\n    set newMessage to make new outgoing message with properties {subject:"Current Top Performer // Nasdaq", content:"Hi,\n\nwie gehabt, hier die aktuellen Top-Performer.\n\nGruß,\nRobert", visible:true}\n    tell newMessage\n        make new to recipient at end of to recipients with properties {address:"recipient@example.com"}\n        tell content\n            make new attachment with properties {file name:"/Users/robertsteinbruck/Library/CloudStorage/Dropbox/Py Assessment/Momentum Trading/Top Performer.xlsx"} at after the last paragraph\n        end tell\n    end tell\n    activate\nend tell\n'], returncode=0)